# Generated by Django 5.2.4 on 2025-08-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
