# Generated by Django 5.2.4 on 2025-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userprofile_id_alter_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
